version: "3.8"

services:
  app:
    build: .
    container_name: just3lines
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    # 개발시에는 코드 변경시 자동 재시작
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload