name: Deploy to GCP

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행
      - feature/deploy-gcp
  workflow_dispatch:  # 수동 실행도 가능하게 함

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
      
    env:
      PROJECT_ID: 'just3lines'
      REGION: 'asia-northeast3'  # GCP 리전 (서울)
      REPO_NAME: 'j3l-docker-registry'  # Artifact Registry 저장소 이름
      IMAGE: 'just3lines-api'
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: 'Checkout repository'
      uses: 'actions/checkout@v4'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'
        
    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ env.PROJECT_ID }}
        workload_identity_provider: 'projects/772476664444/locations/global/workloadIdentityPools/j3l-pool-id/providers/j3l-github-auth'
        service_account: 'just3lines-github@just3lines.iam.gserviceaccount.com'

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }} .
    
    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }}
        
        # 최신 태그도 추가
        docker tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE }}:${{ env.IMAGE_TAG }} \
          ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE }}:latest
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE }}:latest
